version: '3.7'
services:
  postgres:
    container_name: postgres_mks
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
  redis:
    image: redis
    container_name: redis_mks
    ports:
      - '6379:6379'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
